workflows:
  ios-build:
    name: iOS Build
    environment:
      vars:
        PROJECT_NAME: "Howl"               # Replace with your app's name
        SCHEME: "HowlScheme"               # Add your scheme name (or set as environment variable)
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install Dependencies
        script: |
          echo "Complete"  # You can install dependencies here if necessary, like CocoaPods or Carthage
      - name: Build the App
        script: |
          echo "Building the app..."
          xcodebuild -workspace $PROJECT_NAME.xcworkspace -scheme $SCHEME -sdk iphoneos -configuration Release archive -archivePath $PWD/build/$PROJECT_NAME.xcarchive
      - name: Export .ipa File
        script: |
          echo "Exporting .ipa file..."
          xcodebuild -exportArchive -archivePath $PWD/build/$PROJECT_NAME.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build
    artifacts:
      - build/**/*.ipa
      - build/**/*.dSYM.zip
