workflows:
  ios-build:
    name: iOS Build Workflow

    labels:
      - QA

    instance_type: mac_mini_m2
    max_build_duration: 60

    inputs:
      PROJECT_NAME:
        description: "Howl"
        default: "Howl"

      SCHEME:
        description: "Howl"
        default: "Howl"

    environment:
      flutter: stable  # Remove if you're not using Flutter
      xcode: latest

    cache:
      cache_paths:
        - ~/.pub-cache  # If using Flutter, otherwise remove

    triggering:
      events:
        - push
        - pull_request

      branch_patterns:
        - pattern: '*'
          include: true
          source: true

      cancel_previous_builds: false

    scripts:
      - name: Install Dependencies
        script: |
          echo "Installing dependencies..."

      - name: Build the App
        script: |
          echo "Building the app..."
          xcodebuild -project Howl.xcodeproj -scheme Howl -configuration Release archive -archivePath $PWD/build/Howl.xcarchive -allowProvisioningUpdates
      - name: Export IPA
        script: |
          mkdir $PWD/files
          cp -r $PWD/build/Howl.xcarchive/* $PWD/files
          mkdir ./Payload
          mv $PWD/files ./Payload
          zip -r $PWD/Howl.ipa ./Payload 
          ls -lh


    artifacts:
      - Howl.ipa

    publishing:
      email:
        recipients:
          - spoinkosgithub@gmail.com

      scripts:
        - echo 'Post-publish script'
