workflows:
  ios-build:
    name: iOS Build Workflow

    environment:
      xcode: latest  # Ensure you're using the latest version of Xcode

    scripts:
      - name: Install Dependencies
        script: |
          echo "Installing dependencies..."
          pod install || echo "No Podfile found, skipping CocoaPods installation."

      - name: Build the App
        script: |
          echo "Archiving the app..."
          xcodebuild -workspace Howl.xcworkspace \
                     -scheme Howl \
                     -configuration Release \
                     -archivePath $CM_BUILD_DIR/Howl.xcarchive \
                     archive \
                     -allowProvisioningUpdates

      - name: Export IPA
        script: |
          echo "Exporting IPA..."
          mkdir -p $CM_BUILD_DIR/ipa_output
          xcodebuild -exportArchive \
                     -archivePath $CM_BUILD_DIR/Howl.xcarchive \
                     -exportPath $CM_BUILD_DIR/ipa_output \
                     -exportOptionsPlist exportOptions.plist \
                     -allowProvisioningUpdates

      - name: Code Signing Validation
        script: |
          echo "Verifying the signed IPA..."
          IPA_FILE=$(find $CM_BUILD_DIR/ipa_output -name "*.ipa" | head -n 1)
          codesign --verify --verbose $IPA_FILE

    artifacts:
      - $CM_BUILD_DIR/ipa_output/*.ipa

    publishing:
      email:
        recipients:
          - spoinkosgithub@gmail.com
