workflows:
  ios-build:
    name: iOS Build Workflow

    labels:
      - QA

    instance_type: mac_mini_m2
    max_build_duration: 60

    inputs:
      PROJECT_NAME:
        description: "Howl"
        default: "Howl"

      SCHEME:
        description: "Howl"
        default: "Howl"

    environment:
      flutter: stable  # Remove if you're not using Flutter
      xcode: latest

    cache:
      cache_paths:
        - ~/.pub-cache  # If using Flutter, otherwise remove

    triggering:
      events:
        - push
        - pull_request

      branch_patterns:
        - pattern: '*'
          include: true
          source: true

      cancel_previous_builds: false

    scripts:
      - name: Install Dependencies
        script: |
          echo "Installing dependencies..."
          # Uncomment if you're using CocoaPods
          # pod install

      - name: Build the App
        script: |
          echo "Building the app..."
          xcodebuild -project Howl.xcodeproj -scheme Howl -configuration Release archive -archivePath $PWD/build/Howl.xcarchive -allowProvisioningUpdates

      - name: Export .xcarchive
        script: |
          echo "Exporting .xcarchive..."
          # You can skip the export to IPA, just preserve the .xcarchive
          cp -R $PWD/build/Howl.xcarchive $PWD/build/

    artifacts:
      - build/Howl.xcarchive  # Save the xcarchive as an artifact

    publishing:
      email:
        recipients:
          - spoinkosgithub@gmail.com

      scripts:
        - echo 'Post-publish script'
